apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: solar-system-test
  namespace: _[_NAMESPACE_]_
spec:
  healthCheck:
    timeoutSec: 1
    type: HTTP
    requestPath: /
    port: 3000