name: docker-meta-check
on:
    workflow_dispatch: 
    push:
        branches: 
          -  'main'
          -  'feature/*'
        tags:
          - 'v[0-9]+.[0-9]+.[0-9]+'

    pull_request:
        branches:
            -  'main'
            -  'feature/*'  
jobs:
    docker-meta:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        env:
            image: ${{ github.repository }}
            
        permissions: write-all
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ghcr.io/${{ env.image }}
              tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
         
          - name: Login to GitHub Container Registry
            
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         
          - name: Build and push Docker image

            uses: docker/build-push-action@v5
            with:
              context: .
              push: ${{ 
                github.event.base_ref =='refs/heads/main' && 
                github.ref_type == 'tag' }}
              tags: ${{ steps.metadata.outputs.tags }}
              labels: ${{ steps.metadata.outputs.labels }}