name: check git tag events, branched versions
on:
    push: 
        branches: 
            - main
            - feature/*
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    pull_request: 
        branches: 
            - main
            - feature/*
jobs:
    tags_refs:
        runs-on: ubuntu-latest
        steps:
            - name: check the version
              uses: actions/checkout@v4

            - name: check the git tag version
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                    echo ${{ env.GITHUB_CONTEXT }}




