name: Solar System Workflow

on: 
  workflow_dispatch:
  pull_request: 
    types: [ opened ]
    branches: 
      - master

  push:
    branches:
      - main
      - 'feature/*'


env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}  



jobs:
    unit-testing:
       # strategy:

        #    matrix:
        #     node-version: ['18', '19', '20']
        #     os: [ubuntu-latest, windows-latest ]

        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 19
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml


    code-coverage:
        permissions:
          contents: write
          pull-requests: write
          repository-projects: write
        name: code coverage
        runs-on: ubuntu-latest
        steps:
       

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 19
    
        - name: Install Dependencies
          run: npm install
    
        - name: code coverage
          run: npm run coverage
            
        - name: Code Coverage Summary Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: coverage/cobertura-coverage.xml 
            output: both  
            badge: true
            indicators: true
           

        - name: Archive Code Coverage Result
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: Code coverage result
            path: coverage 

         

        - name: Produce the coverage report
          uses: insightsengineering/coverage-action@v2
          with:
            # Path to the Cobertura XML report.
            path: coverage/cobertura-coverage.xml 
            # Minimum total coverage, if you want to the
            # workflow to enforce it as a standard.
            # This has no effect if the `fail` arg is set to `false`.
            threshold: 70
            # Fail the workflow if the minimum code coverage
            # reuqirements are not satisfied.
            fail: false
            # Publish the rendered output as a PR comment
            publish: true
            # Create a coverage diff report.
            diff: true
            # Branch to diff against.
            # Compare the current coverage to the coverage
            # determined on this branch.
            diff-branch: reports
            # This is where the coverage reports for the
            # `diff-branch` are stored.
            # Branch is created if it doesn't already exist'.
            diff-storage: _xml_coverage_reports
            # A custom title that can be added to the code
            # coverage summary in the PR comment.
            coverage-summary-title: "Code Coverage Summary"